# Site settings
title:          Tale
description:    "Minimal Jekyll theme for storytellers"
baseurl:        "/"
url:            "https://howd4ys.github.io"

# Author
author:
  name:         hOwDayS
  url:          https://howd4ys.github.io
  email:        glare789@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
